import { useEffect, useCallback } from 'react';
import Head from 'next/head'
import { useWeb3React } from '@web3-react/core';
import { connector } from '../config/web3';
import Header from '../components/Header';
import styles from '../styles/Home.module.css'

export default function Home() {
  const { activate, active, deactivate, account, error, chainId } = useWeb3React();

  const connect = useCallback((e) => {
    activate(connector);
    localStorage.setItem('previouslyConnected', "true");
  }, [active]);

  const disconnect = () => {
    deactivate();
    localStorage.removeItem('previouslyConnected');
  }

  useEffect(() => {
    if (localStorage.getItem('previouslyConnected')) connect();
  }, [connect]);

  return (
    <div className={styles.container}>
      <Head>
        <title>CryptoApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <Header title="CryptoApp" url="https://nextjs.org" />

        {!active ? (
          <button onClick={connect}>Conectar Wallet</button>
        ) : (
          <>
            <button onClick={disconnect}>Desconectar Wallet</button>
            <p>Wallet conectado: {account}</p>
          </>
        )}

      </main>
    </div>
  )
}
